@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.cuboiddroid.cuboidqs.modules.collapser.handler;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;